#Name: Chase-Miller
#Prog-Purpose: This program computes grades for students using a
#python list (dictionary)
#each student has 3 grades
#each is worth 100 points
#final grade is the average of the three grades

stu = [
    {'name' : "Cho Dianne" ,
     'hw' : 92,
     'mid_exam' : 90,
     'fin_exam' : 91,
     'fin_grade' : 0,
     'ltr_grade' : "X",
     },
    
    {'name': "Anderson Manuel",
     'hw': 89,
     'mid_exam': 92,
     'fin_exam': 94,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Thompson Yani",
     'hw': 63,
     'mid_exam': 74,
     'fin_exam': 59,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Ortiz Graciela",
     'hw': 81,
     'mid_exam': 76,
     'fin_exam': 79,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Wilson Danielle",
     'hw': 100,
     'mid_exam': 89,
     'fin_exam': 94,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Smith Steven",
     'hw': 75,
     'mid_exam': 60,
     'fin_exam': 63,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Johnson Angelo",
     'hw': 91,
     'mid_exam': 71,
     'fin_exam': 61,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Williams Megan",
     'hw': 53,
     'mid_exam': 0,
     'fin_exam': 61,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Brown Johanna",
     'hw': 65,
     'mid_exam': 69,
     'fin_exam': 77,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Jones John",
     'hw': 87,
     'mid_exam': 86,
     'fin_exam': 58,
     'fin_grade': 0,
     'ltr_grade': "X",
      },
    {'name': "Garcia Alicia",
     'hw': 64,
     'mid_exam': 90,
     'fin_exam': 68,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Miller Ronald",
     'hw': 62,
     'mid_exam': 43,
     'fin_exam': 57,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Davis Brian",
     'hw': 99,
     'mid_exam': 72,
     'fin_exam': 96,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Rodriguez Luis",
     'hw': 95,
     'mid_exam': 62,
     'fin_exam': 97,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Martinez Philip",
     'hw': 66,
     'mid_exam': 69,
     'fin_exam': 94,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Hernandez Lakeesha",
     'hw': 78,
     'mid_exam': 59,
     'fin_exam': 64,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Lopez Ellen",
     'hw': 63,
     'mid_exam': 62,
     'fin_exam': 99,
     'fin_grade': 0,
     'ltr_grade': "X",
    },
    {'name': "Gonzalez Lillie",
     'hw': 62,
     'mid_exam': 91,
     'fin_exam': 59,
     'fin_grade': 0,
     'ltr_grade': 'X'},
    {'name': "Wilson Rolando",
     'hw': 0,
     'mid_exam': 54,
     'fin_exam': 58,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Anderson Valerie",
     'hw': 92,
     'mid_exam': 93,
     'fin_exam': 76,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Thomas Armando",
     'hw': 91,
     'mid_exam': 72,
     'fin_exam': 67,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Taylor Emma",
     'hw': 95,
     'mid_exam': 66,
     'fin_exam': 79,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Moore James",
     'hw': 64,
     'mid_exam': 85,
     'fin_exam': 74,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Jackson Jamie",
     'hw': 74,
     'mid_exam': 59,
     'fin_exam': 93,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Cho Ramon",
     'hw': 97,
     'mid_exam': 78,
     'fin_exam': 79,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Lee Tamara'",
     'hw': 68,
     'mid_exam': 68,
     'fin_exam': 73,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Perez Daniel",
     'hw': 63,
     'mid_exam': 72,
     'fin_exam': 59,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Thompson Daniel",
     'hw': 81,
     'mid_exam': 90,
     'fin_exam': 75,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "White Danielle",
     'hw': 58,
     'mid_exam': 68,
     'fin_exam': 66,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Harris Kenneth",
     'hw': 85,
     'mid_exam': 71,
     'fin_exam': 78,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Sanchez Monica",
     'hw': 90,
     'mid_exam': 76,
     'fin_exam': 78,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Clark Anita",
     'hw': 84,
     'mid_exam': 98,
     'fin_exam': 71,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Ramirez Wendy",
     'hw': 73,
     'mid_exam': 57,
     'fin_exam': 100,
     'fin_grade': 0,
     'ltr_grade': "X"},
    {'name': "Lewis George",
     'hw': 58,
     'mid_exam': 77,
     'fin_exam': 85,
     'fin_grade': 0,
     'ltr_grade': "X"},
 
    {'name': "RobFLson Gloria",
      'hw': 68,
      'mid_exam': 77,
      'fin_exam': 72,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
    {'name': "Walker Rhonda",
      'hw': 60,
      'mid_exam': 71,
      'fin_exam': 77,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
    {'name': "Young Mohammed",
      'hw': 63,
      'mid_exam': 84,
      'fin_exam': 74,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Allen April",
      'hw': 57,
      'mid_exam': 60,
      'fin_exam': 77,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Ortiz Carrie",
      'hw': 88,
      'mid_exam': 74,
      'fin_exam': 57,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Wright Christopher",
      'hw': 100,
      'mid_exam': 69,
      'fin_exam': 83,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Scott Gary",
      'hw': 57,
      'mid_exam': 75,
      'fin_exam': 70,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Torres Leroy",
      'hw': 57,
      'mid_exam': 87,
      'fin_exam': 80,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Nguyen Marcus",
      'hw': 100,
      'mid_exam': 63,
      'fin_exam': 57,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Hill Marjorie",
      'hw': 91,
      'mid_exam': 91,
      'fin_exam': 76,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Flores Mark",
      'hw': 95,
      'mid_exam': 95,
      'fin_exam': 72,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Green Jason",
      'hw': 93,
      'mid_exam': 61,
      'fin_exam': 59,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Adams Joseph",
      'hw': 97,
      'mid_exam': 89,
      'fin_exam': 93,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Nelson Leslie",
      'hw': 62,
      'mid_exam': 73,
      'fin_exam': 73,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Baker Anthony",
      'hw': 60,
      'mid_exam': 72,
      'fin_exam': 79,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Hall Esther",
      'hw': 69,
      'mid_exam': 80,
      'fin_exam': 80,
      'fin_grade': 0,
      'ltr_grade': "X"},
 
     {'name': "Rivera Katrina",
      'hw': 72,
      'mid_exam': 86,
      'fin_exam': 99,
      'fin_grade': 0,
      'ltr_grade': "X"},
     {'name' : "Cho Dianne" ,
      'hw' : 92,
      'mid_exam' : 90,
      'fin_exam' : 91,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
     {'name' : "Campbell Matthew" ,
      'hw' : 92,
      'mid_exam' : 74,
      'fin_exam' : 75,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
     {'name' : "Mitchell Nathan" ,
      'hw' : 98,
      'mid_exam' : 78,
      'fin_exam' : 67,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
     {'name' : "Carter Eduardo" ,
      'hw' : 84,
      'mid_exam' : 63,
      'fin_exam' : 77,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
     {'name' : "Roberts Paul" ,
      'hw' : 73,
      'mid_exam' : 80,
      'fin_exam' : 72,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
     {'name' : "Williams Pauline" ,
      'hw' : 83,
      'mid_exam' : 66,
      'fin_exam' : 85,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
     {'name' : "Brown David" ,
      'hw' : 80,
      'mid_exam' : 82,
      'fin_exam' : 84,
      'fin_grade' : 0,
      'ltr_grade' : "X" },
    ]
def main():
    calculate_grades()
    print_grade_report()

def calculate_grades():
    for i in range(len(stu)):
        sum_grades = stu[i]['hw'] + stu[i]['mid_exam'] + stu [i]['fin_exam']
        stu[i]['fin_grade'] = sum_grades / 3

        finalgr = stu[i]['fin_grade']
        if finalgr >= 90:
            lettergrade = 'A'
        elif finalgr >= 80:
            lettergrade = 'B'
        elif finalgr >= 70:
            lettergrade = 'C'
        elif finalgr >= 60:
            lettergrade = 'D'
        else:
            lettergrade = 'F'
        stu[i]['ltr_grade'] = lettergrade

def print_grade_report():
    print("****************** CSC 230 Grade Report *******************")
    print("NAME                  HW\tMID\tFIN\tFINAL GRADE")
    for i in range(len(stu)):
        sname = '{0:<18}'.format(stu[i]['name'])
        hw = str(stu[i]['hw'])
        midex = str(stu[1]['mid_exam'])
        finex = str(stu[1]['fin_exam'])
        fingrade = format(stu[i]['fin_grade'],'6,.2f')
        print ( sname + "\t" + hw + "\t" + midex + "\t" + finex + "\t" +fingrade + " "+ stu[1]['ltr_grade'])

main()
